baseURL = 'https://hanwg.top/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'PaperMod'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  social = true

[params.homeInfoParams]
Title = "Hi there wave"
Content = "Can be Info, links, about..."

[[params.socialIcons]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/hanwuguang/"

[[params.socialIcons]]
name = "GitHub"
url = "https://github.com/hanwg"

[outputs]
home = [ "HTML", "RSS", "JSON" ]